# Generated by Django 4.2.20 on 2025-05-09 13:18

import django.db.models.fields.json
from django.db import migrations, models

import debusine.artifacts.models


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0004_system_image_components'),
    ]
    replaces = [
        ('db', '0146_collectionitem_db_ci_suite_index_path_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(
                models.F('parent_collection'),
                django.db.models.fields.json.KeyTextTransform('path', 'data'),
                condition=models.Q(
                    (
                        'category',
                        debusine.artifacts.models.ArtifactCategory[
                            'REPOSITORY_INDEX'
                        ],
                    ),
                    ('child_type', 'a'),
                    (
                        'parent_category',
                        debusine.artifacts.models.CollectionCategory['SUITE'],
                    ),
                ),
                name='db_ci_suite_index_path_idx',
            ),
        ),
    ]
