# Generated by Django 3.2.19 on 2024-02-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_autopkgtest_task_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestore',
            name='backend',
            field=models.CharField(
                choices=[
                    ('Local', 'Local'),
                    ('ExternalDebianSuite', 'ExternalDebianSuite'),
                ],
                max_length=255,
            ),
        ),
    ]
