# Generated by Django 3.2.19 on 2024-03-05 09:35

from django.db import migrations, models

import debusine.db.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_rename_constraints'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=debusine.db.constraints.JsonDataUniqueConstraint(
                condition=models.Q(
                    ('category', 'debian:environment'),
                    ('removed_at__isnull', True),
                ),
                fields=(
                    "data->>'codename'",
                    "data->>'architecture'",
                    "data->>'variant'",
                    'parent_collection',
                ),
                name='db_collectionitem_unique_debian_environment',
                nulls_distinct=False,
            ),
        ),
    ]
