# Generated by Django 3.2.19 on 2024-05-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0053_debian_environments_typo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workrequest',
            options={
                'ordering': ['id'],
                'permissions': [
                    (
                        'manage_workrequest_priorities',
                        'Can set positive priority adjustments on work requests',
                    )
                ],
            },
        ),
    ]
