# Generated by Django 3.2.19 on 2024-05-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0054_alter_workrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='created_by_work_request',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='db.workrequest',
            ),
        ),
    ]
