# Generated by Django 3.2.19 on 2024-05-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0056_debian_environments_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='expiration_delay',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
