# Generated by Django 3.2.19 on 2024-06-06 11:57

from django.db import migrations, models

import debusine.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0065_worker_worker_type_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(
                choices=[
                    (
                        debusine.tasks.models.WorkerType['EXTERNAL'],
                        debusine.tasks.models.WorkerType['EXTERNAL'],
                    ),
                    (
                        debusine.tasks.models.WorkerType['CELERY'],
                        debusine.tasks.models.WorkerType['CELERY'],
                    ),
                    (
                        debusine.tasks.models.WorkerType['SIGNING'],
                        debusine.tasks.models.WorkerType['SIGNING'],
                    ),
                ],
                default=debusine.tasks.models.WorkerType['EXTERNAL'],
                editable=False,
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='task_type',
            field=models.CharField(
                choices=[
                    (
                        debusine.tasks.models.TaskTypes['WORKER'],
                        debusine.tasks.models.TaskTypes['WORKER'],
                    ),
                    (
                        debusine.tasks.models.TaskTypes['SERVER'],
                        debusine.tasks.models.TaskTypes['SERVER'],
                    ),
                    (
                        debusine.tasks.models.TaskTypes['INTERNAL'],
                        debusine.tasks.models.TaskTypes['INTERNAL'],
                    ),
                    (
                        debusine.tasks.models.TaskTypes['WORKFLOW'],
                        debusine.tasks.models.TaskTypes['WORKFLOW'],
                    ),
                    (
                        debusine.tasks.models.TaskTypes['SIGNING'],
                        debusine.tasks.models.TaskTypes['SIGNING'],
                    ),
                ],
                default=debusine.tasks.models.TaskTypes['WORKER'],
                editable=False,
                max_length=8,
                verbose_name='Type of task to execute',
            ),
        ),
    ]
