# Generated by Django 3.2.19 on 2024-08-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0075_fileinartifact_complete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinartifact',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
