# Generated by Django 3.2.19 on 2024-09-03 14:31

from django.db import migrations, models

import debusine.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0076_fileinartifact_complete_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='task_type',
            field=models.CharField(
                choices=[
                    (
                        debusine.tasks.models.TaskTypes['WORKER'],
                        debusine.tasks.models.TaskTypes['WORKER'],
                    ),
                    (
                        debusine.tasks.models.TaskTypes['SERVER'],
                        debusine.tasks.models.TaskTypes['SERVER'],
                    ),
                    (
                        debusine.tasks.models.TaskTypes['INTERNAL'],
                        debusine.tasks.models.TaskTypes['INTERNAL'],
                    ),
                    (
                        debusine.tasks.models.TaskTypes['WORKFLOW'],
                        debusine.tasks.models.TaskTypes['WORKFLOW'],
                    ),
                    (
                        debusine.tasks.models.TaskTypes['SIGNING'],
                        debusine.tasks.models.TaskTypes['SIGNING'],
                    ),
                    (
                        debusine.tasks.models.TaskTypes['WAIT'],
                        debusine.tasks.models.TaskTypes['WAIT'],
                    ),
                ],
                default=debusine.tasks.models.TaskTypes['WORKER'],
                editable=False,
                max_length=8,
                verbose_name='Type of task to execute',
            ),
        ),
    ]
