# Generated by Django 3.2.19 on 2024-10-03 09:52

from django.db import migrations, models

import debusine.db.models.scopes


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0084_workspace_namespace_by_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[debusine.db.models.scopes.validate_scope_name],
            ),
        ),
    ]
