.TH DEBUSINE\-ADMIN 1
.SH NAME
debusine\-admin \- Administration command for the Debusine server
.SH SYNOPSIS 
Debusine is a general purpose software factory tailored to the needs of a
Debian-based distribution.

debusine\-admin allows management of workers, tokens and more.
.SH USAGE
Please refer to the available documentation:
.IP "\(bu" 4
off-line in the package debusine\-doc: /usr/share/doc/debusine\-doc/html/howtos/set\-up\-debusine\-server.html 
.IP "\(bu" 4
on-line in https://freexian\-team.pages.debian.net/debusine/howtos/set\-up\-debusine\-server.html
.SH "SEE ALSO"
Refer to other man pages such as:
.BR debusine (1),
.BR debusine\-worker (1).
