.TH DEBUSINE\-WORKER 1
.SH NAME
debusine\-worker \- Standalone daemon handling work requests for a debusine server
.SH SYNOPSIS
Debusine is a general purpose software factory tailored to the needs of a
Debian-based distribution.

This package provides the services to run a debusine worker executing work
requests sent by a debusine server.
.SH USAGE
Please refer to the available documentation:
.IP "\(bu" 4
off-line in the package debusine\-doc: /usr/share/doc/debusine\-doc/html/howtos/set\-up\-debusine\-worker.html
.IP "\(bu" 4
on-line in https://freexian\-team.pages.debian.net/debusine/howtos/set\-up\-debusine\-worker.html
.SH "SEE ALSO"
Refer to other man pages such as:
.BR debusine (1),
.BR debusine\-admin (1).
