.TH DEBUSINE\-SIGNING 1
.SH NAME
debusine\-signing \- Signing service for debusine
.SH SYNOPSIS
Debusine is a general purpose software factory tailored to the needs of a
Debian-based distribution.

This package provides a service that holds private keys and uses them to
sign data on behalf of debusine.
.SH "SEE ALSO"
Refer to other man pages such as:
.BR debusine (1),
.BR debusine\-admin (1),
.BR debusine\-worker (1).
