#!/bin/bash

set -e

source debian/tests/utils/add-debusine-log-files-to-artifacts.sh

debian/tests/utils/integration-tests-setup-debusine-all.sh

debian/tests/integration-tests-task-simplesystemimagebuild.py -v
