#!/bin/bash

set -e

debian/tests/utils/check-namespace-support

source debian/tests/utils/add-debusine-log-files-to-artifacts.sh

debian/tests/utils/integration-tests-setup-debusine-all.sh
debian/tests/utils/integration-tests-setup-debusine-signing.sh

pytest --rootdir=. -c /dev/null -v debian/tests/integration-tests-task-signing.py
