#!/bin/sh

set -e

service postgresql start
service redis-server start

runuser -u postgres -- createuser --createdb debusine-server

cp -a pyproject.toml "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"

cat << EOF >> /etc/debusine/server/test.py

# Use paths from the package (e.g. logs into /var/log/debusine/server)
from .pkg_paths import *  # noqa
EOF

runuser -u debusine-server -- pytest --rootdir=/usr/lib/python3/dist-packages -c pyproject.toml -v --pyargs debusine.db debusine.django debusine.project debusine.server debusine.test debusine.web
