debusine/client/dput_ng/skel/hooks/*.json /usr/share/dput-ng/hooks/
debusine/client/dput_ng/skel/metas/*.json /etc/dput.d/metas/
debusine/client/dput_ng/skel/profiles/*.json /etc/dput.d/profiles/
debusine/client/dput_ng/skel/uploaders/*.json /usr/share/dput-ng/uploaders/
usr/bin/debusine

# For dependency calculation; we'll remove this later to avoid conflicts.
usr/lib/python3*/dist-packages/debusine-*.dist-info/
